"""Rich HTML report generator."""

from __future__ import annotations

from pathlib import Path
from datetime import datetime

from jinja2 import Environment, BaseLoader
from pygments import highlight
from pygments.lexers import VbNetLexer, get_lexer_by_name
from pygments.formatters import HtmlFormatter

from ..models import FormulaCategory, SheetVisibility, WorkbookAnalysis


class HTMLReportBuilder:
    """Generates a rich, interactive HTML report."""

    def __init__(self, analysis: WorkbookAnalysis, output_dir: Path):
        """Initialize the builder.

        Args:
            analysis: The workbook analysis results
            output_dir: Directory to write the report
        """
        self.analysis = analysis
        self.output_dir = output_dir
        self.env = Environment(loader=BaseLoader())

    def build(self) -> Path:
        """Generate the HTML report.

        Returns:
            Path to the generated report.html
        """
        self.output_dir.mkdir(parents=True, exist_ok=True)

        html = self._generate_html()
        report_path = self.output_dir / "report.html"
        report_path.write_text(html, encoding="utf-8")

        return report_path

    def _generate_html(self) -> str:
        """Generate the complete HTML document."""
        a = self.analysis

        # Generate sections
        summary_section = self._generate_summary_section()
        sheets_section = self._generate_sheets_section()
        formulas_section = self._generate_formulas_section()
        features_section = self._generate_features_section()
        vba_section = self._generate_vba_section() if a.vba_modules else ""
        pq_section = self._generate_power_query_section() if a.power_queries else ""
        issues_section = self._generate_issues_section()
        screenshots_section = self._generate_screenshots_section() if a.screenshots else ""

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{self._escape(a.file_name)} - Excel Analysis Report</title>
    {self._get_styles()}
</head>
<body>
    <nav id="sidebar">
        <h2>Navigation</h2>
        <ul>
            <li><a href="#summary">Summary</a></li>
            <li><a href="#sheets">Sheets ({len(a.sheets)})</a></li>
            <li><a href="#formulas">Formulas ({len(a.formulas)})</a></li>
            <li><a href="#features">Features</a></li>
            {"<li><a href='#vba'>VBA (" + str(len(a.vba_modules)) + ")</a></li>" if a.vba_modules else ""}
            {"<li><a href='#power-query'>Power Query (" + str(len(a.power_queries)) + ")</a></li>" if a.power_queries else ""}
            <li><a href="#issues">Issues</a></li>
            {"<li><a href='#screenshots'>Screenshots</a></li>" if a.screenshots else ""}
        </ul>
        <div id="search-container">
            <input type="text" id="search" placeholder="Search..." />
        </div>
    </nav>

    <main>
        <header>
            <h1>{self._escape(a.file_name)}</h1>
            <p class="subtitle">Excel Workbook Analysis Report</p>
            <p class="generated">Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
        </header>

        {summary_section}
        {sheets_section}
        {formulas_section}
        {features_section}
        {vba_section}
        {pq_section}
        {issues_section}
        {screenshots_section}

        <footer>
            <p>Generated by Excel Analyzer for Claude Code</p>
        </footer>
    </main>

    {self._get_scripts()}
</body>
</html>"""

    def _generate_summary_section(self) -> str:
        """Generate the summary section."""
        a = self.analysis

        # Count by visibility
        visible = sum(1 for s in a.sheets if s.visibility == SheetVisibility.VISIBLE)
        hidden = sum(1 for s in a.sheets if s.visibility == SheetVisibility.HIDDEN)
        very_hidden = sum(1 for s in a.sheets if s.visibility == SheetVisibility.VERY_HIDDEN)

        # Formula categories
        cats = {}
        for f in a.formulas:
            cats[f.category.value] = cats.get(f.category.value, 0) + 1

        formula_breakdown = ""
        for cat, count in sorted(cats.items(), key=lambda x: -x[1]):
            formula_breakdown += f"<li>{cat}: {count}</li>"

        features_list = ""
        if a.conditional_formats:
            features_list += f"<li>Conditional Formatting ({len(a.conditional_formats)} rules)</li>"
        if a.data_validations:
            features_list += f"<li>Data Validations ({len(a.data_validations)} rules)</li>"
        if a.tables:
            features_list += f"<li>Tables ({len(a.tables)})</li>"
        if a.pivot_tables:
            features_list += f"<li>Pivot Tables ({len(a.pivot_tables)})</li>"
        if a.charts:
            features_list += f"<li>Charts ({len(a.charts)})</li>"
        if a.vba_modules:
            features_list += f"<li>VBA Macros ({len(a.vba_modules)} modules)</li>"
        if a.power_queries:
            features_list += f"<li>Power Query ({len(a.power_queries)} queries)</li>"
        if a.has_dax:
            features_list += f"<li>Power Pivot/DAX</li>"
        if a.comments:
            features_list += f"<li>Comments ({len(a.comments)})</li>"
        if a.hyperlinks:
            features_list += f"<li>Hyperlinks ({len(a.hyperlinks)})</li>"
        if a.controls:
            features_list += f"<li>Form Controls ({len(a.controls)})</li>"

        return f"""
        <section id="summary" class="section">
            <h2>Summary</h2>

            <div class="card-grid">
                <div class="card">
                    <h3>File Info</h3>
                    <table class="info-table">
                        <tr><th>File Name</th><td>{self._escape(a.file_name)}</td></tr>
                        <tr><th>File Size</th><td>{self._format_size(a.file_size)}</td></tr>
                        <tr><th>Macro Enabled</th><td>{"Yes" if a.is_macro_enabled else "No"}</td></tr>
                    </table>
                </div>

                <div class="card">
                    <h3>Sheets</h3>
                    <div class="stat-large">{len(a.sheets)}</div>
                    <ul class="stat-breakdown">
                        <li>Visible: {visible}</li>
                        <li>Hidden: {hidden}</li>
                        <li>Very Hidden: {very_hidden}</li>
                    </ul>
                </div>

                <div class="card">
                    <h3>Formulas</h3>
                    <div class="stat-large">{len(a.formulas)}</div>
                    <ul class="stat-breakdown">
                        {formula_breakdown}
                    </ul>
                </div>

                <div class="card">
                    <h3>Features</h3>
                    <ul class="feature-list">
                        {features_list if features_list else "<li>No advanced features</li>"}
                    </ul>
                </div>
            </div>

            {self._generate_warnings_block()}
        </section>
        """

    def _generate_warnings_block(self) -> str:
        """Generate warnings/errors block if any."""
        a = self.analysis

        if not a.errors and not a.warnings:
            return ""

        items = ""
        for e in a.errors:
            items += f'<li class="error">{self._escape(e.extractor)}: {self._escape(e.message)}</li>'
        for w in a.warnings:
            items += f'<li class="warning">{self._escape(w.extractor)}: {self._escape(w.message)}</li>'

        return f"""
        <div class="warnings-block">
            <h4>Extraction Notes</h4>
            <ul>{items}</ul>
        </div>
        """

    def _generate_sheets_section(self) -> str:
        """Generate the sheets section."""
        rows = ""
        for s in self.analysis.sheets:
            features = []
            if s.has_formulas:
                features.append('<span class="badge">Formulas</span>')
            if s.has_charts:
                features.append('<span class="badge">Charts</span>')
            if s.has_pivots:
                features.append('<span class="badge">Pivots</span>')
            if s.has_tables:
                features.append('<span class="badge">Tables</span>')
            if s.has_conditional_formatting:
                features.append('<span class="badge">CF</span>')
            if s.has_data_validation:
                features.append('<span class="badge">DV</span>')

            vis_class = s.visibility.value.replace("_", "-")
            features_html = " ".join(features) if features else "-"

            color_indicator = ""
            if s.tab_color:
                color_indicator = f'<span class="color-dot" style="background-color: {s.tab_color}"></span>'

            rows += f"""
            <tr class="sheet-row" data-sheet="{self._escape(s.name)}">
                <td>{s.index + 1}</td>
                <td>{color_indicator}{self._escape(s.name)}</td>
                <td><span class="visibility {vis_class}">{s.visibility.value}</span></td>
                <td>{s.row_count}</td>
                <td>{s.col_count}</td>
                <td>{features_html}</td>
            </tr>
            """

        return f"""
        <section id="sheets" class="section">
            <h2>Sheets</h2>
            <table class="data-table sortable">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Visibility</th>
                        <th>Rows</th>
                        <th>Cols</th>
                        <th>Features</th>
                    </tr>
                </thead>
                <tbody>
                    {rows}
                </tbody>
            </table>
        </section>
        """

    def _generate_formulas_section(self) -> str:
        """Generate the formulas section."""
        # Named ranges
        named_ranges_html = ""
        lambdas = [n for n in self.analysis.named_ranges if n.is_lambda]
        regular = [n for n in self.analysis.named_ranges if not n.is_lambda]

        if lambdas:
            lambda_items = ""
            for n in lambdas:
                lambda_items += f"""
                <div class="lambda-def">
                    <h4>{self._escape(n.name)}</h4>
                    <pre><code>{self._escape(n.value)}</code></pre>
                </div>
                """
            named_ranges_html += f"""
            <div class="subsection">
                <h3>LAMBDA Functions ({len(lambdas)})</h3>
                {lambda_items}
            </div>
            """

        if regular:
            regular_rows = ""
            for n in regular[:50]:
                scope = n.scope or "Global"
                regular_rows += f"""
                <tr>
                    <td>{self._escape(n.name)}</td>
                    <td><code>{self._escape(n.value[:60])}</code></td>
                    <td>{scope}</td>
                </tr>
                """
            more = f"<p><em>...and {len(regular) - 50} more</em></p>" if len(regular) > 50 else ""
            named_ranges_html += f"""
            <div class="subsection">
                <h3>Named Ranges ({len(regular)})</h3>
                <table class="data-table">
                    <thead>
                        <tr><th>Name</th><th>Value</th><th>Scope</th></tr>
                    </thead>
                    <tbody>{regular_rows}</tbody>
                </table>
                {more}
            </div>
            """

        # Formulas table
        formula_rows = ""
        for f in self.analysis.formulas[:100]:
            preview = f.formula_clean[:80]
            if len(f.formula_clean) > 80:
                preview += "..."
            formula_rows += f"""
            <tr>
                <td>{self._escape(f.location.sheet)}</td>
                <td>{f.location.cell}</td>
                <td><span class="badge">{f.category.value}</span></td>
                <td><code class="formula">{self._escape(preview)}</code></td>
            </tr>
            """

        more_formulas = ""
        if len(self.analysis.formulas) > 100:
            more_formulas = f"<p><em>Showing first 100 of {len(self.analysis.formulas)} formulas</em></p>"

        return f"""
        <section id="formulas" class="section">
            <h2>Formulas</h2>

            {named_ranges_html}

            <div class="subsection">
                <h3>All Formulas ({len(self.analysis.formulas)})</h3>
                {more_formulas}
                <table class="data-table sortable">
                    <thead>
                        <tr>
                            <th>Sheet</th>
                            <th>Cell</th>
                            <th>Category</th>
                            <th>Formula</th>
                        </tr>
                    </thead>
                    <tbody>
                        {formula_rows}
                    </tbody>
                </table>
            </div>
        </section>
        """

    def _generate_features_section(self) -> str:
        """Generate the features section."""
        subsections = ""

        # Conditional Formatting
        if self.analysis.conditional_formats:
            cf_rows = ""
            for cf in self.analysis.conditional_formats[:50]:
                cf_rows += f"""
                <tr>
                    <td>{self._escape(cf.range)}</td>
                    <td>{cf.rule_type.value}</td>
                    <td>{self._escape(cf.description)}</td>
                </tr>
                """
            subsections += f"""
            <div class="subsection">
                <h3>Conditional Formatting ({len(self.analysis.conditional_formats)})</h3>
                <table class="data-table">
                    <thead><tr><th>Range</th><th>Type</th><th>Description</th></tr></thead>
                    <tbody>{cf_rows}</tbody>
                </table>
            </div>
            """

        # Data Validations
        if self.analysis.data_validations:
            dv_rows = ""
            for dv in self.analysis.data_validations[:50]:
                formula = dv.formula1 or "-"
                if len(formula) > 50:
                    formula = formula[:50] + "..."
                dv_rows += f"""
                <tr>
                    <td>{self._escape(dv.range)}</td>
                    <td>{dv.type}</td>
                    <td><code>{self._escape(formula)}</code></td>
                </tr>
                """
            subsections += f"""
            <div class="subsection">
                <h3>Data Validations ({len(self.analysis.data_validations)})</h3>
                <table class="data-table">
                    <thead><tr><th>Range</th><th>Type</th><th>Formula/List</th></tr></thead>
                    <tbody>{dv_rows}</tbody>
                </table>
            </div>
            """

        # Tables
        if self.analysis.tables:
            table_cards = ""
            for t in self.analysis.tables:
                cols = ", ".join(t.columns[:5])
                if len(t.columns) > 5:
                    cols += f" (+{len(t.columns) - 5} more)"
                table_cards += f"""
                <div class="feature-card">
                    <h4>{self._escape(t.display_name)}</h4>
                    <p><strong>Sheet:</strong> {self._escape(t.sheet)}</p>
                    <p><strong>Range:</strong> {t.range}</p>
                    <p><strong>Columns:</strong> {self._escape(cols)}</p>
                </div>
                """
            subsections += f"""
            <div class="subsection">
                <h3>Structured Tables ({len(self.analysis.tables)})</h3>
                <div class="feature-grid">{table_cards}</div>
            </div>
            """

        # Pivot Tables
        if self.analysis.pivot_tables:
            pivot_cards = ""
            for p in self.analysis.pivot_tables:
                pivot_cards += f"""
                <div class="feature-card">
                    <h4>{self._escape(p.name)}</h4>
                    <p><strong>Sheet:</strong> {self._escape(p.sheet)}</p>
                    <p><strong>Location:</strong> {p.location}</p>
                    {"<p><strong>Rows:</strong> " + ", ".join(p.row_fields) + "</p>" if p.row_fields else ""}
                    {"<p><strong>Values:</strong> " + ", ".join(p.data_fields) + "</p>" if p.data_fields else ""}
                </div>
                """
            subsections += f"""
            <div class="subsection">
                <h3>Pivot Tables ({len(self.analysis.pivot_tables)})</h3>
                <div class="feature-grid">{pivot_cards}</div>
            </div>
            """

        # Charts
        if self.analysis.charts:
            chart_rows = ""
            for c in self.analysis.charts:
                chart_rows += f"""
                <tr>
                    <td>{self._escape(c.name)}</td>
                    <td>{self._escape(c.sheet)}</td>
                    <td>{c.chart_type}</td>
                    <td>{self._escape(c.title or '-')}</td>
                </tr>
                """
            subsections += f"""
            <div class="subsection">
                <h3>Charts ({len(self.analysis.charts)})</h3>
                <table class="data-table">
                    <thead><tr><th>Name</th><th>Sheet</th><th>Type</th><th>Title</th></tr></thead>
                    <tbody>{chart_rows}</tbody>
                </table>
            </div>
            """

        # Controls
        if self.analysis.controls:
            control_rows = ""
            for c in self.analysis.controls:
                macro = c.macro or "-"
                control_rows += f"""
                <tr>
                    <td>{self._escape(c.name)}</td>
                    <td>{self._escape(c.sheet)}</td>
                    <td>{c.control_type}</td>
                    <td><code>{self._escape(macro)}</code></td>
                </tr>
                """
            subsections += f"""
            <div class="subsection">
                <h3>Form Controls ({len(self.analysis.controls)})</h3>
                <table class="data-table">
                    <thead><tr><th>Name</th><th>Sheet</th><th>Type</th><th>Macro</th></tr></thead>
                    <tbody>{control_rows}</tbody>
                </table>
            </div>
            """

        # Connections
        if self.analysis.connections:
            conn_rows = ""
            for c in self.analysis.connections:
                conn_str = c.connection_string or "-"
                if len(conn_str) > 60:
                    conn_str = conn_str[:60] + "..."
                conn_rows += f"""
                <tr>
                    <td>{self._escape(c.name)}</td>
                    <td>{c.connection_type}</td>
                    <td><code>{self._escape(conn_str)}</code></td>
                </tr>
                """
            subsections += f"""
            <div class="subsection">
                <h3>Data Connections ({len(self.analysis.connections)})</h3>
                <table class="data-table">
                    <thead><tr><th>Name</th><th>Type</th><th>Connection</th></tr></thead>
                    <tbody>{conn_rows}</tbody>
                </table>
            </div>
            """

        if not subsections:
            subsections = "<p>No advanced features found in this workbook.</p>"

        return f"""
        <section id="features" class="section">
            <h2>Features</h2>
            {subsections}
        </section>
        """

    def _generate_vba_section(self) -> str:
        """Generate the VBA section."""
        if not self.analysis.vba_modules:
            return ""

        modules_html = ""
        for m in self.analysis.vba_modules:
            # Syntax highlight the code
            try:
                highlighted = highlight(m.code, VbNetLexer(), HtmlFormatter(nowrap=True))
            except Exception:
                highlighted = self._escape(m.code)

            procs = ", ".join(m.procedures) if m.procedures else "None"

            modules_html += f"""
            <div class="vba-module collapsible">
                <div class="module-header" onclick="toggleCollapse(this)">
                    <h4>{self._escape(m.name)}</h4>
                    <span class="module-info">{m.module_type} | {m.line_count} lines</span>
                </div>
                <div class="module-content collapsed">
                    <p><strong>Procedures:</strong> {self._escape(procs)}</p>
                    <pre class="code-block"><code>{highlighted}</code></pre>
                </div>
            </div>
            """

        return f"""
        <section id="vba" class="section">
            <h2>VBA Modules ({len(self.analysis.vba_modules)})</h2>
            {modules_html}
        </section>
        """

    def _generate_power_query_section(self) -> str:
        """Generate the Power Query section."""
        if not self.analysis.power_queries:
            return ""

        queries_html = ""
        for q in self.analysis.power_queries:
            # Try to highlight M code
            try:
                lexer = get_lexer_by_name("text")  # M doesn't have a standard lexer
                highlighted = highlight(q.formula, lexer, HtmlFormatter(nowrap=True))
            except Exception:
                highlighted = self._escape(q.formula)

            queries_html += f"""
            <div class="pq-query collapsible">
                <div class="query-header" onclick="toggleCollapse(this)">
                    <h4>{self._escape(q.name)}</h4>
                </div>
                <div class="query-content collapsed">
                    {"<p>" + self._escape(q.description) + "</p>" if q.description else ""}
                    <pre class="code-block"><code>{highlighted}</code></pre>
                </div>
            </div>
            """

        return f"""
        <section id="power-query" class="section">
            <h2>Power Query ({len(self.analysis.power_queries)})</h2>
            {queries_html}
        </section>
        """

    def _generate_issues_section(self) -> str:
        """Generate the issues section."""
        subsections = ""

        # Error cells
        if self.analysis.error_cells:
            error_rows = ""
            for e in self.analysis.error_cells[:50]:
                formula = e.formula or "-"
                error_rows += f"""
                <tr>
                    <td>{self._escape(e.location.address)}</td>
                    <td class="error-type">{e.error_type.value}</td>
                    <td><code>{self._escape(formula)}</code></td>
                </tr>
                """
            more = f"<p><em>...and {len(self.analysis.error_cells) - 50} more</em></p>" if len(self.analysis.error_cells) > 50 else ""
            subsections += f"""
            <div class="subsection">
                <h3>Error Cells ({len(self.analysis.error_cells)})</h3>
                <table class="data-table">
                    <thead><tr><th>Location</th><th>Error</th><th>Formula</th></tr></thead>
                    <tbody>{error_rows}</tbody>
                </table>
                {more}
            </div>
            """

        # External references
        if self.analysis.external_refs:
            ext_rows = ""
            for ref in self.analysis.external_refs[:50]:
                status = '<span class="badge error">Broken</span>' if ref.is_broken else ""
                source = ref.source_cell.address if ref.source_cell.cell else "-"
                ext_rows += f"""
                <tr>
                    <td>{source}</td>
                    <td>{self._escape(ref.target_workbook)}</td>
                    <td>{self._escape(ref.target_sheet or '-')}</td>
                    <td>{status}</td>
                </tr>
                """
            subsections += f"""
            <div class="subsection">
                <h3>External References ({len(self.analysis.external_refs)})</h3>
                <table class="data-table">
                    <thead><tr><th>Source</th><th>Workbook</th><th>Sheet</th><th>Status</th></tr></thead>
                    <tbody>{ext_rows}</tbody>
                </table>
            </div>
            """

        if not subsections:
            subsections = "<p>No issues detected.</p>"

        return f"""
        <section id="issues" class="section">
            <h2>Issues</h2>
            {subsections}
        </section>
        """

    def _generate_screenshots_section(self) -> str:
        """Generate the screenshots section."""
        if not self.analysis.screenshots:
            return ""

        gallery = ""
        for s in self.analysis.screenshots:
            gallery += f"""
            <div class="screenshot-card">
                <h4>{self._escape(s.sheet)}</h4>
                <a href="screenshots/{s.path.name}" target="_blank">
                    <img src="screenshots/{s.path.name}" alt="{self._escape(s.sheet)}" loading="lazy" />
                </a>
            </div>
            """

        return f"""
        <section id="screenshots" class="section">
            <h2>Screenshots</h2>
            <div class="screenshot-gallery">
                {gallery}
            </div>
        </section>
        """

    def _get_styles(self) -> str:
        """Get the embedded CSS styles."""
        return """
    <style>
        :root {
            --bg: #f8f9fa;
            --card-bg: #ffffff;
            --text: #212529;
            --text-muted: #6c757d;
            --border: #dee2e6;
            --primary: #0d6efd;
            --success: #198754;
            --warning: #ffc107;
            --error: #dc3545;
            --sidebar-width: 250px;
        }

        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            background: var(--bg);
            color: var(--text);
            line-height: 1.6;
        }

        #sidebar {
            position: fixed;
            left: 0;
            top: 0;
            width: var(--sidebar-width);
            height: 100vh;
            background: var(--card-bg);
            border-right: 1px solid var(--border);
            padding: 1rem;
            overflow-y: auto;
        }

        #sidebar h2 {
            font-size: 1rem;
            margin-bottom: 1rem;
            color: var(--text-muted);
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }

        #sidebar ul {
            list-style: none;
        }

        #sidebar li {
            margin-bottom: 0.5rem;
        }

        #sidebar a {
            color: var(--text);
            text-decoration: none;
            padding: 0.5rem;
            display: block;
            border-radius: 4px;
        }

        #sidebar a:hover {
            background: var(--bg);
        }

        #search-container {
            margin-top: 1rem;
            padding-top: 1rem;
            border-top: 1px solid var(--border);
        }

        #search {
            width: 100%;
            padding: 0.5rem;
            border: 1px solid var(--border);
            border-radius: 4px;
            font-size: 0.9rem;
        }

        main {
            margin-left: var(--sidebar-width);
            padding: 2rem;
            max-width: 1200px;
        }

        header {
            margin-bottom: 2rem;
            padding-bottom: 1rem;
            border-bottom: 2px solid var(--border);
        }

        header h1 {
            font-size: 2rem;
            margin-bottom: 0.25rem;
        }

        .subtitle {
            color: var(--text-muted);
            font-size: 1.1rem;
        }

        .generated {
            color: var(--text-muted);
            font-size: 0.9rem;
        }

        .section {
            background: var(--card-bg);
            border-radius: 8px;
            padding: 1.5rem;
            margin-bottom: 1.5rem;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
        }

        .section h2 {
            margin-bottom: 1rem;
            padding-bottom: 0.5rem;
            border-bottom: 1px solid var(--border);
        }

        .subsection {
            margin-top: 1.5rem;
        }

        .subsection h3 {
            font-size: 1.1rem;
            margin-bottom: 0.75rem;
            color: var(--text-muted);
        }

        .card-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 1rem;
        }

        .card {
            background: var(--bg);
            border-radius: 6px;
            padding: 1rem;
        }

        .card h3 {
            font-size: 0.9rem;
            color: var(--text-muted);
            margin-bottom: 0.5rem;
        }

        .stat-large {
            font-size: 2.5rem;
            font-weight: bold;
            color: var(--primary);
        }

        .stat-breakdown {
            list-style: none;
            font-size: 0.9rem;
            color: var(--text-muted);
        }

        .feature-list {
            list-style: none;
        }

        .feature-list li {
            padding: 0.25rem 0;
        }

        .feature-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 1rem;
        }

        .feature-card {
            background: var(--bg);
            border-radius: 6px;
            padding: 1rem;
        }

        .feature-card h4 {
            margin-bottom: 0.5rem;
        }

        .feature-card p {
            font-size: 0.9rem;
            margin-bottom: 0.25rem;
        }

        .data-table {
            width: 100%;
            border-collapse: collapse;
            font-size: 0.9rem;
        }

        .data-table th,
        .data-table td {
            padding: 0.75rem;
            text-align: left;
            border-bottom: 1px solid var(--border);
        }

        .data-table th {
            background: var(--bg);
            font-weight: 600;
            position: sticky;
            top: 0;
        }

        .data-table tr:hover {
            background: var(--bg);
        }

        .info-table {
            width: 100%;
        }

        .info-table th {
            text-align: left;
            font-weight: normal;
            color: var(--text-muted);
            padding: 0.25rem 0;
        }

        .info-table td {
            text-align: right;
            font-weight: 500;
        }

        .badge {
            display: inline-block;
            padding: 0.2rem 0.5rem;
            border-radius: 4px;
            font-size: 0.75rem;
            font-weight: 500;
            background: var(--bg);
            color: var(--text-muted);
        }

        .badge.error {
            background: #ffeef0;
            color: var(--error);
        }

        .visibility {
            padding: 0.2rem 0.5rem;
            border-radius: 4px;
            font-size: 0.8rem;
        }

        .visibility.visible {
            background: #d4edda;
            color: var(--success);
        }

        .visibility.hidden {
            background: #fff3cd;
            color: #856404;
        }

        .visibility.very-hidden {
            background: #ffeef0;
            color: var(--error);
        }

        .color-dot {
            display: inline-block;
            width: 12px;
            height: 12px;
            border-radius: 50%;
            margin-right: 0.5rem;
            vertical-align: middle;
        }

        code, .formula {
            font-family: "SF Mono", Monaco, Consolas, monospace;
            font-size: 0.85em;
            background: var(--bg);
            padding: 0.1rem 0.3rem;
            border-radius: 3px;
        }

        .code-block {
            background: #1e1e1e;
            color: #d4d4d4;
            padding: 1rem;
            border-radius: 6px;
            overflow-x: auto;
            font-size: 0.85rem;
            line-height: 1.5;
        }

        .code-block code {
            background: none;
            padding: 0;
        }

        .collapsible .module-header,
        .collapsible .query-header {
            cursor: pointer;
            padding: 1rem;
            background: var(--bg);
            border-radius: 6px;
            margin-bottom: 0.5rem;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .collapsible .module-header:hover,
        .collapsible .query-header:hover {
            background: var(--border);
        }

        .collapsible .module-content,
        .collapsible .query-content {
            padding: 1rem;
        }

        .collapsed {
            display: none;
        }

        .lambda-def {
            background: var(--bg);
            padding: 1rem;
            border-radius: 6px;
            margin-bottom: 1rem;
        }

        .lambda-def h4 {
            margin-bottom: 0.5rem;
            color: var(--primary);
        }

        .warnings-block {
            background: #fff3cd;
            border: 1px solid #ffc107;
            border-radius: 6px;
            padding: 1rem;
            margin-top: 1rem;
        }

        .warnings-block h4 {
            margin-bottom: 0.5rem;
        }

        .warnings-block ul {
            list-style: none;
        }

        .warnings-block li.error {
            color: var(--error);
        }

        .warnings-block li.warning {
            color: #856404;
        }

        .error-type {
            color: var(--error);
            font-weight: 500;
        }

        .screenshot-gallery {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
            gap: 1rem;
        }

        .screenshot-card {
            background: var(--bg);
            border-radius: 6px;
            overflow: hidden;
        }

        .screenshot-card h4 {
            padding: 0.75rem;
            background: var(--card-bg);
            border-bottom: 1px solid var(--border);
        }

        .screenshot-card img {
            width: 100%;
            height: auto;
            display: block;
        }

        footer {
            margin-top: 2rem;
            padding-top: 1rem;
            border-top: 1px solid var(--border);
            text-align: center;
            color: var(--text-muted);
            font-size: 0.9rem;
        }

        @media (max-width: 768px) {
            #sidebar {
                position: static;
                width: 100%;
                height: auto;
                border-right: none;
                border-bottom: 1px solid var(--border);
            }

            main {
                margin-left: 0;
            }
        }
    </style>
        """

    def _get_scripts(self) -> str:
        """Get the embedded JavaScript."""
        return """
    <script>
        // Collapsible sections
        function toggleCollapse(header) {
            const content = header.nextElementSibling;
            content.classList.toggle('collapsed');
        }

        // Search functionality
        document.getElementById('search').addEventListener('input', function(e) {
            const query = e.target.value.toLowerCase();
            const rows = document.querySelectorAll('tbody tr');

            rows.forEach(row => {
                const text = row.textContent.toLowerCase();
                row.style.display = text.includes(query) ? '' : 'none';
            });
        });

        // Smooth scroll
        document.querySelectorAll('#sidebar a').forEach(link => {
            link.addEventListener('click', function(e) {
                e.preventDefault();
                const target = document.querySelector(this.getAttribute('href'));
                if (target) {
                    target.scrollIntoView({ behavior: 'smooth' });
                }
            });
        });

        // Expand all code blocks on page load for visibility
        // Comment this out if you want them collapsed by default
        // document.querySelectorAll('.collapsed').forEach(el => el.classList.remove('collapsed'));
    </script>
        """

    def _escape(self, text: str) -> str:
        """Escape HTML special characters."""
        if not text:
            return ""
        return (
            str(text)
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
            .replace("'", "&#39;")
        )

    def _format_size(self, size_bytes: int) -> str:
        """Format file size in human-readable form."""
        for unit in ["B", "KB", "MB", "GB"]:
            if size_bytes < 1024:
                return f"{size_bytes:.1f} {unit}"
            size_bytes /= 1024
        return f"{size_bytes:.1f} TB"
